"""
A Collatz sequence is generated by repeatedly applying the following rules to an integer and then to each resulting integer in turn:

If even: divide by 2.
If odd: multiply by 3, then add 1.
The Collatz algorithm has been tested and found to always reach 1 for all positive integers.

Create a function that, when given two positive integers a b, returns the string "a" if integer a took fewer steps to reach 1 than b when passed through the Collatz sequence, or "b" if integer b took fewer steps to reach 1 than a.

Examples
collatz(10, 15) ➞ "a"
# Because 10.0 - 5.0 - 16.0 - 8.0 - 4.0 - 2.0 - 1.0: 6 steps
# 15.0 - 46.0 - 23.0 - 70.0 - 35.0 - 106.0 - 53.0 - 160.0 - 80.0 - 40.0 - 20.0 - 10.0 - 5.0 - 16.0 - 8.0 - 4.0 - 2.0 - 1.0: 17 steps

collatz(13, 16) ➞ "b"

collatz(53782, 72534) ➞ "b"
"""

def collatz(a, b):
    current_a = a
    count_a = 0
    current_b = b
    count_b = 0

    while current_a != 1:
        if current_a % 2 == 0:
            current_a = current_a / 2
        else:
            current_a = (current_a * 3) + 1
        count_a += 1

    while current_b != 1:
        if current_b % 2 == 0:
            current_b = current_b / 2
        else:
            current_b = (current_b * 3) + 1
        count_b += 1

    if count_a < count_b:
        return "a"
    else:
        return "b"

print(collatz(10, 15))
print(collatz(13, 16))
print(collatz(53782, 72534))
